// <auto-generated />
namespace OrderingApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class OO1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OO1));
        
        string IMigrationMetadata.Id
        {
            get { return "201904090932037_OO1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
